title: Blog | Zeyu Bai
email: clarencehwite98@outlook.com
description: >-
baseurl: "https://clarencewhite.github.io"
url: "/baizeyu.info"
github_username: ClarenceWhite

# Build settings
theme: minima

# outline generator
plugins:
    - jekyll-toc
