title: Blog | Zeyu Bai
email: clarencehwite98@outlook.com
description: >-
baseurl: ""
url: ""
twitter_username:
github_username: ClarenceWhite

# Build settings
theme: minima
highlighter: rouge

plugins:
    - jekyll-sass-converter