title: Blog | Zeyu Bai
email: clarencehwite98@outlook.com
description: >-
baseurl: "baizeyu.info"
url: "baizeyu.info"
twitter_username:
github_username: ClarenceWhite

# Build settings
theme: minima

# outline generator
plugins:
    - jekyll-toc
